# Generated by Django 4.0.6 on 2022-08-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_delete_auditoriacuenta_delete_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField(blank=True, null=True)),
                ('customer_surname', models.TextField(blank=True, null=True)),
                ('customer_dni', models.TextField(blank=True, db_column='customer_DNI', null=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('balance', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
