# Generated by Django 4.0.6 on 2022-08-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('numero_tarjeta', models.IntegerField(blank=True, null=True)),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('fecha_otorgamiento', models.IntegerField(blank=True, null=True)),
                ('fecha_expiracion', models.IntegerField(blank=True, null=True)),
                ('tipo_tarjeta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TARJETA',
                'managed': False,
            },
        ),
    ]
